# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e50ccb39568dc370ba68d48cc496402c45ce2c48944fb465fef0090e3c9855ba85103ce54fa325c1762a39be9e0de699025e4cbc84df138002fb0423af4647a4

test:
  secret_key_base: 057fba044bec346448ae12d78f36df18a298e39b42a31911b25fe581ac81f40083b35500ace0746d40a574639ad2f9f2e91243142841192f1c1891c8a94b2f2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
